### PR TITLE
make compilation work when we haven't used namespace std

### PR DESCRIPTION
**Pull request by ekg**
Also makes a change to a protobuf call so that it works on libprotobuf-dev/bionic,now 3.0.0-9.1ubuntu1 amd64.

### CODE REVIEW

**Comment by adamnovak** [comment]
@ekg Have you tested this in a vg build? I had to *remove* that argument to that Protobuf call that you are adding back to get this to build with vg's recent Protobuf upgrade.

Could we just downgrade vg's Protobuf to match what's in Bionic? Or rip out vg's protobuf and just get it from the system now?

**Comment by adamnovak** [comment]
Wait, I forgot that we ripped out vg's Protobuf and it now lives in here...

How are you building libvgio against Bionic's Protobuf? Can you just commit that and let us rip out our vendor'd Protobuf altogether?

**Comment by adamnovak** [comment]
Wait, no, I'm *still* wrong. The proto *file* lives here, but the protobuf *dependency* is provided by vg itself.

We should just rip it out of vg and use system Protobuf. If libvgio builds against what's in Bionic, I don't see a reason to keep providing our own.

**Comment by ekg** [comment]
We should provide a recipe for getting the correct protobuf and other build
tools using conda. This is what is done with GraphAligner (which builds a
vg protobuf reading library) and it works well. Otherwise system tools are
ideal.

**Comment by adamnovak** [comment]
It looks like GraphAligner picks up its Protobuf from conda using pkg-config, so presumably we want to keep doing that here as well, and then move to doing that in vg also instead of including a submodule.

So I think that means we should go ahead and merge this. Then we update vg to use system Protobuf instead of its own when we update it to this version of libvgio.

**Pull request merged**
